{
    "openapi": "3.0.0",
    "info": {
        "title": "L5 OpenApi",
        "description": "L5 Swagger OpenApi description",
        "license": {
            "name": "Apache 2.0",
            "url": "https://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "0.0.1",
        "x-logo": {
            "url": "https://via.placeholder.com/190x90.png?text=L5-Swagger"
        }
    },
    "paths": {
        "/api/movies": {
            "get": {
                "tags": [
                    "Movies"
                ],
                "summary": "Get one random movie",
                "responses": {
                    "200": {
                        "description": "One random movie",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "examples": {
                                    "result": {
                                        "summary": "Result json",
                                        "value": {
                                            "en_title": "Out Of The Furnace",
                                            "release_date": "2013",
                                            "synopsis": "When Rodney Baze mysteriously disappears and law enforcement doesn't follow through fast enough, his older brother, Russell, takes matters into his own hands to find justice.",
                                            "fr_title": "Les Brasiers De La Colère",
                                            "de_title": "Auge Um Auge",
                                            "es_title": "Out Of The Furnace",
                                            "it_title": "Il Fuoco Della Vendetta - Out Of The Furnace",
                                            "ja_title": "ファーナス/訣別の朝",
                                            "zh_title": "逃出熔炉",
                                            "ru_title": "Из пекла",
                                            "slug": "out-of-the-furnace"
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "post": {
                "tags": [
                    "Movies"
                ],
                "summary": "Create a new movie (Need an api token)",
                "description": "<b>THIS ACTION IS FOR DOCUMENTATION ONLY, PLEASE USE IT FROM WITHIN THE APP OR YOUR OWN ONLY.</b> <br /> Required fields are <b>en_title</b>, <b>synopsis</b> and <b>release_date</b>. Optionnal fields are <b>fr_title</b>, <b>es_title</b>, <b>de_title</b>, <b>it_title</b>, <b>ja_title</b>, <b>ru_title</b>, <b>zh_title</b>",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "required": [
                                    "en_title",
                                    "synopsis",
                                    "release_date"
                                ],
                                "properties": {
                                    "en_title": {
                                        "type": "string"
                                    },
                                    "synopsis": {
                                        "type": "string"
                                    },
                                    "release_date": {
                                        "type": "string"
                                    },
                                    "fr_title": {
                                        "type": "string"
                                    }
                                },
                                "type": "object"
                            },
                            "example": {
                                "en_title": "Out Of The Furnace",
                                "synopsis": "When Rodney Baze mysteriously disappears and law enforcement doesn't follow through fast enough, his older brother, Russell, takes matters into his own hands to find justice.",
                                "release_date": "2013",
                                "fr_title": "Les brasiers de la colère",
                                "de_title": "Auge Um Auge",
                                "es_title": "Out Of The Furnace",
                                "it_title": "Il Fuoco Della Vendetta - Out Of The Furnace",
                                "ja_title": "ファーナス/訣別の朝",
                                "zh_title": "逃出熔炉",
                                "ru_title": "Из пекла"
                            }
                        }
                    }
                },
                "responses": {
                    "409": {
                        "description": "Movie already exists",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "examples": {
                                    "result": {
                                        "summary": "Result json",
                                        "value": "A Movie resource already exists with this en_title"
                                    }
                                }
                            }
                        }
                    },
                    "201": {
                        "description": "Movie created",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "examples": {
                                    "result": {
                                        "summary": "Result json",
                                        "value": {
                                            "en_title": "Out Of The Furnace",
                                            "slug": "out-of-the-furnace",
                                            "synopsis": "When Rodney Baze mysteriously disappears and law enforcement doesn't follow through fast enough, his older brother, Russell, takes matters into his own hands to find justice.",
                                            "release_date": "2013",
                                            "fr_title": "Les brasiers de la colère",
                                            "de_title": "Auge Um Auge",
                                            "es_title": "Out Of The Furnace",
                                            "it_title": "Il Fuoco Della Vendetta - Out Of The Furnace",
                                            "ja_title": "ファーナス/訣別の朝",
                                            "zh_title": "逃出熔炉",
                                            "ru_title": "Из пекла"
                                        }
                                    }
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "sanctum": []
                    }
                ]
            }
        },
        "/api/movies/{movie}": {
            "get": {
                "tags": [
                    "Movies"
                ],
                "summary": "Get one movie resource",
                "parameters": [
                    {
                        "name": "movie",
                        "in": "path",
                        "description": "Slug of the movie",
                        "required": true,
                        "schema": {
                            "type": "string"
                        },
                        "examples": {
                            "Out Of The Furnace": {
                                "summary": "Out Of The Furnace sluggified",
                                "value": "out-of-the-furnace"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "The movie resource",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "examples": {
                                    "result": {
                                        "summary": "Result json",
                                        "value": {
                                            "en_title": "Out Of The Furnace",
                                            "release_date": "2013",
                                            "synopsis": "When Rodney Baze mysteriously disappears and law enforcement doesn't follow through fast enough, his older brother, Russell, takes matters into his own hands to find justice.",
                                            "fr_title": "Les Brasiers De La Colère",
                                            "de_title": "Auge Um Auge",
                                            "es_title": "Out Of The Furnace",
                                            "it_title": "Il Fuoco Della Vendetta - Out Of The Furnace",
                                            "ja_title": "ファーナス/訣別の朝",
                                            "zh_title": "逃出熔炉",
                                            "ru_title": "Из пекла",
                                            "slug": "out-of-the-furnace"
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "patch": {
                "tags": [
                    "Movies"
                ],
                "summary": "Update a movie title (Need an api token)",
                "description": "<b>THIS ACTION IS FOR DOCUMENTATION ONLY, PLEASE USE IT FROM WITHIN THE APP OR YOUR OWN ONLY.</b> <br /> One or multiple fields from <b>fr_title</b>, <b>es_title</b>, <b>de_title</b>, <b>it_title</b>, <b>ja_title</b>, <b>ru_title</b> or <b>zh_title</b>",
                "parameters": [
                    {
                        "name": "movie",
                        "in": "path",
                        "description": "Slug of the movie",
                        "required": true,
                        "schema": {
                            "type": "string"
                        },
                        "examples": {
                            "Out Of The Furnace": {
                                "summary": "Out Of The Furnace sluggified",
                                "value": "out-of-the-furnace"
                            }
                        }
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {},
                            "example": {
                                "fr_title": "Les brasiers de la colère"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Movie title updated",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "examples": {
                                    "result": {
                                        "summary": "Result json",
                                        "value": {
                                            "en_title": "Out Of The Furnace",
                                            "release_date": "2013",
                                            "synopsis": "When Rodney Baze mysteriously disappears and law enforcement doesn't follow through fast enough, his older brother, Russell, takes matters into his own hands to find justice.",
                                            "fr_title": "Les Brasiers De La Colère",
                                            "de_title": "Auge Um Auge",
                                            "es_title": "Out Of The Furnace",
                                            "it_title": "Il Fuoco Della Vendetta - Out Of The Furnace",
                                            "ja_title": "ファーナス/訣別の朝",
                                            "zh_title": "逃出熔炉",
                                            "ru_title": "Из пекла",
                                            "slug": "out-of-the-furnace"
                                        }
                                    }
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "sanctum": []
                    }
                ]
            }
        },
        "/api/user": {
            "get": {
                "tags": [
                    "User"
                ],
                "summary": "Get your user information (Need a token api)",
                "description": "azazaz",
                "responses": {
                    "200": {
                        "description": "user and userToken object"
                    }
                },
                "security": [
                    {
                        "sanctum": []
                    }
                ]
            }
        }
    },
    "tags": [
        {
            "name": "Movies",
            "description": "Anything you can do with movies"
        },
        {
            "name": "User",
            "description": "Get your user informations"
        }
    ],
    "components": {
        "securitySchemes": {
            "sanctum": {
                "type": "apiKey",
                "description": "Enter your apiKey like : Bearer 1|o8vzgdAQu0QUjGGbflR5G4x8snri0ZhylLqEfuju",
                "name": "Authorization",
                "in": "header"
            }
        }
    }
}